name: Check update for any-sync-tools

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_dispatch:

jobs:
  check-update-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ./.github/actions/check-pkg-update
        with:
          nix_path: "pkgs/any-sync/any-sync-tools.nix"
