name: Check update for any-sync-coordinator

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_dispatch:

jobs:
  check-update-coordinator:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-pkg-update.yml
        with:
          nix_path: "pkgs/any-sync/any-sync-coordinator.nix"
