name: Check update for any-sync-consensus

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_dispatch:

jobs:
  check-update-consensus:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-pkg-update
        with:
          nix_path: "pkgs/any-sync/any-sync-consensus.nix"
